### PR TITLE
Make easy git updates of the repo

### PR DESCRIPTION
**Pull request by josefcoap**
Currently is what I use to don't need to make the setup again of identity, target_ips and variables
Easy but effective

### CODE REVIEW

**Comment by valentin-lup** [comment]
We had the same idea 👍 
Added this as a command in the latest version of the scripts...

**Comment by josefcoap** [comment]
Perfect, you will update the doc with it?

**Comment by josefcoap** [comment]
@valentin-lup Can we make that the script itself run a contrab to check every hour if the script repo has new version a execute ./scripts.sh github_pull alone

**Comment by valentin-lup** [comment]
Done & done :)

**Pull request closed without merging**
