### PR TITLE
variables.cfg smart placeholders

### PR DESCRIPTION
**Pull request by koen84**
Using $HOME & $USER as initial values would be smart, a they should good for most people and therefore more userfriendly to people new to linux.

### CODE REVIEW

**Comment by koen84** [comment]
I know this is not a bugfix, but a significant amount of "help me" will be avoided altogether (or at least easier).

**Comment by koen84** [comment]
This merged PR was undone ?

**Comment by valentin-lup** [comment]
Hey. Yes... It was generating problems for remote install. Will consider an improvement in this area though ASAP !

**Comment by koen84** [comment]
Good to know.  My idea was to put something that would work for a majority of users (as a starting point) and in particular those with little linux expertise, while leaving the variables.cfg for editing by those who want custom settings.  Not sure how many folks use the remote option ?  And those are probably smart enough to edit the file as to their needs ?

**Pull request merged**
